name: Build and Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        uses: actions/download-artifact@v2
        with:
          name: dist-artifact
          path: ./dist

      - name: Build
        run: npm run build

      - name: Check package version
        id: cpv
        uses: PostHog/check-package-version@v2
        with:
          path: ./dist

      - name: Echo versions
        run: |
          echo "Committed version: ${{ steps.cpv.outputs.committed-version }}"
          echo "Published version: ${{ steps.cpv.outputs.published-version }}"

      - name: NPM Publish (@pezzo/llm-toolkit)
        if: steps.cpv.outputs.is-new-version == 'true'
        run: |
          version=$(node -p "require('./package.json').version")
          if [[ $version == *"alpha"* ]]; then
            npm publish --access public --tag alpha
          else
            npm publish --access public
          fi
        working-directory: dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
